load test.maude
load ../examples/dam-ctrl/dam-ctrl.maude

mod DAM-PRED is
    pr DAM-CTRL .

    var S : SpillwayId .
    var O : Aperture .
    var SC : Spillways .

    op openSpillways : Spillways -> Nat .
    eq openSpillways(empty) = 0 .
    eq openSpillways([ S,O ] SC) = if O =/= close then 1 + openSpillways(SC) else openSpillways(SC) fi .
endm

erew in TEST-CONTEXT : test(
    "../examples/dam-ctrl/dam-ctrl.maude",
    "../examples/dam-ctrl/complete.constraints",
    'DAM-CTRL, 'DAM-PRED,
    "../examples/dam-ctrl/fixed/dam-ctrl_complete.maude") .

quit