load test.maude
load ../examples/dam-controller/dam-controller.maude

mod DAM-CONTROLLER-PRED is
    pr DAM-CONTROLLER .

    var S : SpillwayId .
    var O : Aperture .
    var SC : Spillways .

    op openSpillways : Spillways -> Nat .
    eq openSpillways(empty) = 0 .
    eq openSpillways([ S,O ] SC) = if O =/= close then 1 + openSpillways(SC) else openSpillways(SC) fi .
endm

erew in TEST-CONTEXT : test(
    "../examples/dam-controller/dam-controller.maude",
    "../examples/dam-controller/state-7.constraints",
    'DAM-CONTROLLER, 'DAM-CONTROLLER-PRED,
    "../examples/dam-controller/fixed/dam-controller_state-7.maude") .

quit