load test.maude
load ../examples/dam/dam.maude

mod DAM-PRED is
    pr DAM .

    var S : SpillwayId .
    var O : Aperture .
    var SC : Spillways .

    op openSpillways : Spillways -> Nat .
    eq openSpillways(empty) = 0 .
    eq openSpillways([ S,O ] SC) = if O =/= close then 1 + openSpillways(SC) else openSpillways(SC) fi .
endm

erew in TEST-CONTEXT : test(
    "../examples/dam/dam.maude",
    "../examples/dam/state-7.constraints",
    'DAM, 'DAM-PRED,
    "../examples/dam/fixed/dam_state-7.maude") .

quit