load test.maude
load ../examples/dam/dam.maude

mod DAM-PRED is
    pr DAM .

    var S : SpillwayId .
    var O : Aperture .
    var SC : Spillways .

    op openSpillways : Spillways -> Nat .
    eq openSpillways(empty) = 0 .
    eq openSpillways([ S,O ] SC) = if O =/= close then 1 + openSpillways(SC) else openSpillways(SC) fi .
endm

select TEST-CONTEXT .

erew writeToFile("../examples/dam/fixed/dam_state.maude", 
    fix('DAM, 'DAM-PRED, readFileToEnd("../examples/dam/state.constraints"))) .

quit