package es.upv.vrain.elp.strass.dto;

public enum ErrorCode {
	CONTAINS_COMMANDS,
	MISSING_REQUIRED_ARGUMENTS,
	TIMED_OUT,
	NATIVE_EXECUTION_ERROR,
	MAUDE_PROVIDED_DIAGNOSTIC,
	CORE_CANNOT_COMPLETE_EXECUTION,
	CONSTRAINT_PARSE_FAILURE
}
